import CalendarEvent from '../models/CalendarEvent.js';
import Baby from '../models/Baby.js';

// Standard vaccination schedule (age in months)
const VACCINATION_SCHEDULE = [
  { age: 0, title: 'Birth Vaccines', description: 'Hepatitis B (1st dose)' },
  { age: 2, title: '2-Month Vaccines', description: 'DTaP, Hib, IPV, PCV13, Rotavirus' },
  { age: 4, title: '4-Month Vaccines', description: 'DTaP, Hib, IPV, PCV13, Rotavirus' },
  { age: 6, title: '6-Month Vaccines', description: 'DTaP, Hib, PCV13, Rotavirus, Hepatitis B' },
  { age: 12, title: '12-Month Vaccines', description: 'MMR, Varicella, Hepatitis A, PCV13' },
  { age: 15, title: '15-Month Vaccines', description: 'DTaP, Hib' },
  { age: 18, title: '18-Month Vaccines', description: 'Hepatitis A (2nd dose)' },
  { age: 24, title: '2-Year Checkup', description: 'General health checkup' }
];

// Standard milestone schedule
const MILESTONE_SCHEDULE = [
  { age: 1, title: 'First Month', description: 'Can lift head briefly, responds to sounds' },
  { age: 2, title: 'Social Smiles', description: 'Begins to smile at people' },
  { age: 3, title: 'Head Control', description: 'Can hold head steady' },
  { age: 4, title: 'Reaching & Grasping', description: 'Reaches for toys' },
  { age: 6, title: 'Sitting Up', description: 'Can sit without support' },
  { age: 9, title: 'Crawling', description: 'May begin to crawl' },
  { age: 12, title: 'First Birthday', description: 'May take first steps, says simple words' },
  { age: 18, title: 'Walking & Talking', description: 'Walks independently, says several words' },
  { age: 24, title: 'Running & Sentences', description: 'Runs, begins to use 2-word sentences' }
];

// Generate vaccination schedule for a baby
export const generateVaccinationSchedule = async (babyId) => {
  try {
    const baby = await Baby.findById(babyId);
    if (!baby || !baby.birthDate) {
      throw new Error('Baby or birth date not found');
    }

    const birthDate = new Date(baby.birthDate);
    const events = [];

    for (const vaccine of VACCINATION_SCHEDULE) {
      const eventDate = new Date(birthDate);
      eventDate.setMonth(eventDate.getMonth() + vaccine.age);

      events.push({
        babyId,
        title: vaccine.title,
        description: vaccine.description,
        date: eventDate,
        type: 'vaccination',
        autoGenerated: true,
        reminder: true,
        reminderDays: 3
      });
    }

    // Insert events that don't already exist
    for (const event of events) {
      const existing = await CalendarEvent.findOne({
        babyId,
        title: event.title,
        type: 'vaccination',
        autoGenerated: true
      });

      if (!existing) {
        await CalendarEvent.create(event);
      }
    }

    return events.length;
  } catch (error) {
    throw error;
  }
};

// Generate milestone schedule for a baby
export const generateMilestoneSchedule = async (babyId) => {
  try {
    const baby = await Baby.findById(babyId);
    if (!baby || !baby.birthDate) {
      throw new Error('Baby or birth date not found');
    }

    const birthDate = new Date(baby.birthDate);
    const events = [];

    for (const milestone of MILESTONE_SCHEDULE) {
      const eventDate = new Date(birthDate);
      eventDate.setMonth(eventDate.getMonth() + milestone.age);

      events.push({
        babyId,
        title: milestone.title,
        description: milestone.description,
        date: eventDate,
        type: 'milestone',
        autoGenerated: true,
        reminder: false
      });
    }

    // Insert events that don't already exist
    for (const event of events) {
      const existing = await CalendarEvent.findOne({
        babyId,
        title: event.title,
        type: 'milestone',
        autoGenerated: true
      });

      if (!existing) {
        await CalendarEvent.create(event);
      }
    }

    return events.length;
  } catch (error) {
    throw error;
  }
};

// Add a calendar event
export const addCalendarEvent = async (eventData) => {
  try {
    const event = await CalendarEvent.create(eventData);
    return event;
  } catch (error) {
    throw error;
  }
};

// Get events for a baby
export const getCalendarEvents = async (babyId, startDate = null, endDate = null) => {
  try {
    const query = { babyId };

    if (startDate || endDate) {
      query.date = {};
      if (startDate) query.date.$gte = new Date(startDate);
      if (endDate) query.date.$lte = new Date(endDate);
    }

    const events = await CalendarEvent.find(query).sort({ date: 1 });
    return events;
  } catch (error) {
    throw error;
  }
};

// Get upcoming events (next N events)
export const getUpcomingEvents = async (babyId, limit = 5) => {
  try {
    const now = new Date();
    const events = await CalendarEvent.find({
      babyId,
      date: { $gte: now },
      completed: false
    })
      .sort({ date: 1 })
      .limit(limit);

    return events;
  } catch (error) {
    throw error;
  }
};

// Get events by month
export const getEventsByMonth = async (babyId, year, month) => {
  try {
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 0, 23, 59, 59);

    const events = await CalendarEvent.find({
      babyId,
      date: { $gte: startDate, $lte: endDate }
    }).sort({ date: 1 });

    return events;
  } catch (error) {
    throw error;
  }
};

// Update calendar event
export const updateCalendarEvent = async (eventId, updates) => {
  try {
    const event = await CalendarEvent.findByIdAndUpdate(
      eventId,
      updates,
      { new: true, runValidators: true }
    );
    return event;
  } catch (error) {
    throw error;
  }
};

// Mark event as completed
export const markEventCompleted = async (eventId, completed = true) => {
  try {
    const event = await CalendarEvent.findByIdAndUpdate(
      eventId,
      { completed },
      { new: true }
    );
    return event;
  } catch (error) {
    throw error;
  }
};

// Delete calendar event
export const deleteCalendarEvent = async (eventId) => {
  try {
    await CalendarEvent.findByIdAndDelete(eventId);
  } catch (error) {
    throw error;
  }
};

// Get events requiring reminder
export const getEventsForReminder = async (babyId) => {
  try {
    const now = new Date();
    const events = await CalendarEvent.find({
      babyId,
      reminder: true,
      completed: false
    });

    const upcomingReminders = events.filter(event => {
      const eventDate = new Date(event.date);
      const reminderDate = new Date(eventDate);
      reminderDate.setDate(reminderDate.getDate() - (event.reminderDays || 1));
      
      return now >= reminderDate && now <= eventDate;
    });

    return upcomingReminders;
  } catch (error) {
    throw error;
  }
};
