import AsyncStorage from '@react-native-async-storage/async-storage';

const API_BASE_URL = 'http://192.168.1.27:5000/api';

export interface CalendarEvent {
  _id: string;
  babyId: string;
  title: string;
  description?: string;
  date: string;
  time?: string;
  type: 'vaccination' | 'checkup' | 'milestone' | 'medication' | 'appointment' | 'other';
  completed: boolean;
  reminder: boolean;
  reminderDays: number;
  autoGenerated: boolean;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AddEventData {
  babyId: string;
  title: string;
  description?: string;
  date: string;
  time?: string;
  type: 'vaccination' | 'checkup' | 'milestone' | 'medication' | 'appointment' | 'other';
  reminder?: boolean;
  reminderDays?: number;
  notes?: string;
}

// Get authorization header
const getAuthHeader = async () => {
  const token = await AsyncStorage.getItem('token');
  return {
    'Authorization': `Bearer ${token}`,
    'Content-Type': 'application/json',
  };
};

// Add a calendar event
export const addCalendarEvent = async (eventData: AddEventData): Promise<CalendarEvent> => {
  try {
    const headers = await getAuthHeader();
    const response = await fetch(`${API_BASE_URL}/calendar/event`, {
      method: 'POST',
      headers,
      body: JSON.stringify(eventData),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.message || 'Failed to add calendar event');
    }

    const event = await response.json();
    
    // Automatically check for notifications after adding event
    try {
      await fetch(`${API_BASE_URL}/calendar/trigger-notifications`, {
        method: 'POST',
      });
      console.log('Auto-triggered notification check after adding event');
    } catch (notifError) {
      console.log('Error triggering notifications:', notifError);
      // Don't fail the whole operation if notification check fails
    }
    
    return event;
  } catch (error) {
    console.error('Error adding calendar event:', error);
    throw error;
  }
};

// Get all events for a baby
export const getCalendarEvents = async (babyId: string, startDate?: string, endDate?: string): Promise<CalendarEvent[]> => {
  try {
    const headers = await getAuthHeader();
    let url = `${API_BASE_URL}/calendar/baby/${babyId}`;
    
    const params = new URLSearchParams();
    if (startDate) params.append('startDate', startDate);
    if (endDate) params.append('endDate', endDate);
    if (params.toString()) url += `?${params.toString()}`;

    const response = await fetch(url, { headers });

    if (!response.ok) {
      throw new Error('Failed to fetch calendar events');
    }

    return await response.json();
  } catch (error) {
    console.error('Error fetching calendar events:', error);
    return [];
  }
};

// Get upcoming events
export const getUpcomingEvents = async (babyId: string, limit: number = 5): Promise<CalendarEvent[]> => {
  try {
    const headers = await getAuthHeader();
    const response = await fetch(`${API_BASE_URL}/calendar/baby/${babyId}/upcoming?limit=${limit}`, { headers });

    if (!response.ok) {
      throw new Error('Failed to fetch upcoming events');
    }

    return await response.json();
  } catch (error) {
    console.error('Error fetching upcoming events:', error);
    return [];
  }
};

// Get events for a specific month
export const getMonthEvents = async (babyId: string, year: number, month: number): Promise<CalendarEvent[]> => {
  try {
    const headers = await getAuthHeader();
    const response = await fetch(`${API_BASE_URL}/calendar/baby/${babyId}/${year}/${month}`, { headers });

    if (!response.ok) {
      throw new Error('Failed to fetch month events');
    }

    return await response.json();
  } catch (error) {
    console.error('Error fetching month events:', error);
    return [];
  }
};

// Update a calendar event
export const updateCalendarEvent = async (eventId: string, updates: Partial<AddEventData>): Promise<CalendarEvent> => {
  try {
    const headers = await getAuthHeader();
    const response = await fetch(`${API_BASE_URL}/calendar/event/${eventId}`, {
      method: 'PUT',
      headers,
      body: JSON.stringify(updates),
    });

    if (!response.ok) {
      throw new Error('Failed to update calendar event');
    }

    return await response.json();
  } catch (error) {
    console.error('Error updating calendar event:', error);
    throw error;
  }
};

// Mark event as completed/uncompleted
export const toggleEventCompleted = async (eventId: string, completed: boolean): Promise<CalendarEvent> => {
  try {
    const headers = await getAuthHeader();
    const response = await fetch(`${API_BASE_URL}/calendar/event/${eventId}/complete`, {
      method: 'PATCH',
      headers,
      body: JSON.stringify({ completed }),
    });

    if (!response.ok) {
      throw new Error('Failed to mark event');
    }

    return await response.json();
  } catch (error) {
    console.error('Error marking event:', error);
    throw error;
  }
};

// Delete a calendar event
export const deleteCalendarEvent = async (eventId: string): Promise<void> => {
  try {
    const headers = await getAuthHeader();
    const response = await fetch(`${API_BASE_URL}/calendar/event/${eventId}`, {
      method: 'DELETE',
      headers,
    });

    if (!response.ok) {
      throw new Error('Failed to delete calendar event');
    }
  } catch (error) {
    console.error('Error deleting calendar event:', error);
    throw error;
  }
};

// Generate vaccination schedule for a baby
export const generateVaccinationSchedule = async (babyId: string): Promise<{ message: string; eventsCreated: number }> => {
  try {
    const headers = await getAuthHeader();
    const response = await fetch(`${API_BASE_URL}/calendar/baby/${babyId}/generate-vaccinations`, {
      method: 'POST',
      headers,
    });

    if (!response.ok) {
      throw new Error('Failed to generate vaccination schedule');
    }

    return await response.json();
  } catch (error) {
    console.error('Error generating vaccination schedule:', error);
    throw error;
  }
};

// Generate milestone schedule for a baby
export const generateMilestoneSchedule = async (babyId: string): Promise<{ message: string; eventsCreated: number }> => {
  try {
    const headers = await getAuthHeader();
    const response = await fetch(`${API_BASE_URL}/calendar/baby/${babyId}/generate-milestones`, {
      method: 'POST',
      headers,
    });

    if (!response.ok) {
      throw new Error('Failed to generate milestone schedule');
    }

    return await response.json();
  } catch (error) {
    console.error('Error generating milestone schedule:', error);
    throw error;
  }
};

// Get events that need reminders
export const getEventReminders = async (babyId: string): Promise<CalendarEvent[]> => {
  try {
    const headers = await getAuthHeader();
    const response = await fetch(`${API_BASE_URL}/calendar/baby/${babyId}/reminders`, { headers });

    if (!response.ok) {
      throw new Error('Failed to fetch reminders');
    }

    return await response.json();
  } catch (error) {
    console.error('Error fetching reminders:', error);
    return [];
  }
};
