import React, { useEffect, useState } from "react";
import { View, ScrollView, StyleSheet, TouchableOpacity, Text, Alert, Image } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { useRouter, useFocusEffect } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import Header from "./Header";
import Footer from "./Footer";
import BabyMonitorStream from "../components/BabyMonitorStream";
import SoundPlayer from "../components/SoundPlayer";
import SoundLibraryModal from "../components/SoundLibraryModal";
import SleepHistoryModal from "../components/SleepHistoryModal";
import GrowthTrackingModal from "../components/GrowthTrackingModal";
import CalendarModal from "../components/CalendarModal";
import { Sound } from "../services/soundService";
import ChatbotModal from "../components/ChatbotModal";
import { getGrowthRecords, getLatestGrowthRecord, addGrowthRecord, GrowthRecord } from "../services/growthService";
import { getUpcomingEvents, CalendarEvent, generateVaccinationSchedule, generateMilestoneSchedule } from "../services/calendarService";
import { getRecentEntries, JournalEntry } from "../services/journalService";

const DashboardPage: React.FC = () => {
  const router = useRouter();
  const [babyName, setBabyName] = useState("");
  const [childInitial, setChildInitial] = useState("?");
  const [avatarColor, setAvatarColor] = useState("#00CFFF");
  const [avatarImage, setAvatarImage] = useState<string | null>(null);
  const [babyId, setBabyId] = useState<string | null>(null);
  const [isLibraryOpen, setIsLibraryOpen] = useState(false);
  const [selectedSound, setSelectedSound] = useState<Sound | null>(null);
  const [chatOpen, setChatOpen] = useState(false);
  const [sleepHistoryOpen, setSleepHistoryOpen] = useState(false);
  const [growthTrackingOpen, setGrowthTrackingOpen] = useState(false);
  const [calendarOpen, setCalendarOpen] = useState(false);
  const [upcomingEvents, setUpcomingEvents] = useState<CalendarEvent[]>([]);
  const [hasAutoGeneratedEvents, setHasAutoGeneratedEvents] = useState(false);
  const [currentWeight, setCurrentWeight] = useState("--");
  const [currentLength, setCurrentLength] = useState("--");
  const [growthRecords, setGrowthRecords] = useState<GrowthRecord[]>([]);
  const [birthWeight, setBirthWeight] = useState<number | null>(null);
  const [birthLength, setBirthLength] = useState<number | null>(null);
  const [birthDate, setBirthDate] = useState<Date | null>(null);
  const [recentMemories, setRecentMemories] = useState<JournalEntry[]>([]);

  const loadBabyForParent = async () => {
    const parentId = await AsyncStorage.getItem("parentId");
    console.log("Loading baby for parentId:", parentId);
    
    if (!parentId) {
      console.warn("No parentId found in AsyncStorage");
      return;
    }

    const token = await AsyncStorage.getItem("token");

    try {
  const response = await fetch(`http://192.168.1.10:5000/api/baby/parent/${parentId}`, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });
      
      console.log("Baby fetch response status:", response.status);
      
      if (!response.ok) {
        const errorData = await response.json();
        console.error("Failed to fetch baby data:", errorData);
        throw new Error("Failed to fetch baby data");
      }

      const data = await response.json();
      console.log("Baby data received:", data);
      
      // API returns an array of babies
      if (data && Array.isArray(data) && data.length > 0) {
        // Check if there's a selected baby ID in AsyncStorage
        const selectedBabyId = await AsyncStorage.getItem("selectedBabyId");
        
        // Find the selected baby, or default to the first one
        let baby;
        if (selectedBabyId) {
          baby = data.find((b: any) => b._id === selectedBabyId);
        }
        if (!baby) {
          baby = data[0]; // Fallback to first baby if selected not found
        }
        
        if (baby && baby.name) {
          setBabyName(baby.name);
          setChildInitial(baby.name.charAt(0).toUpperCase());
          setBabyId(baby._id);
          console.log("Baby name set to:", baby.name);
          
          // Load avatar data from backend
          setAvatarColor(baby.avatarColor || "#00CFFF");
          setAvatarImage(baby.avatarImage ? `http://192.168.1.10:5000${baby.avatarImage}` : null);
          
          // Store birth data
          console.log("Baby birth data - birthWeight:", baby.birthWeight, "birthLength:", baby.birthLength, "birthDate:", baby.birthDate);
          if (baby.birthWeight) setBirthWeight(baby.birthWeight);
          if (baby.birthLength) setBirthLength(baby.birthLength);
          if (baby.birthDate) setBirthDate(new Date(baby.birthDate));
          
          // Load growth records
          loadGrowthData(baby._id, baby.birthWeight, baby.birthLength);
          
          // Load upcoming calendar events
          loadUpcomingEvents(baby._id);
          
          // Load recent journal entries
          loadRecentMemories(baby._id);
        }
      } else {
        console.warn("No baby found for this parent");
      }
    } catch (error) {
      console.error("Error fetching baby data:", error);
    }
  };

  // Load baby data on mount
  useEffect(() => {
    loadBabyForParent();
  }, []);

  // Reload baby data when returning to dashboard (to pick up newly added babies or changed selection)
  useFocusEffect(
    React.useCallback(() => {
      loadBabyForParent();
    }, [])
  );

  const loadUpcomingEvents = async (babyId: string) => {
    try {
      // Fetch more events to ensure we have 3 incomplete ones after filtering
      const events = await getUpcomingEvents(babyId, 10);
      // Check if auto-generated events exist
      const hasAutoGen = events.some(event => event.autoGenerated);
      setHasAutoGeneratedEvents(hasAutoGen);
      // Filter out completed events from dashboard
      const incompleteEvents = events.filter(event => !event.completed);
      // Take only first 3 incomplete events
      setUpcomingEvents(incompleteEvents.slice(0, 3));
      console.log("Loaded upcoming events:", incompleteEvents.length, "incomplete out of", events.length, "total");
    } catch (error) {
      console.log("Error loading upcoming events:", error);
    }
  };

  const loadRecentMemories = async (babyId: string) => {
    try {
      const entries = await getRecentEntries(babyId, 2);
      setRecentMemories(entries);
      console.log("Loaded recent memories:", entries.length);
    } catch (error) {
      console.error("Error loading recent memories:", error);
    }
  };

  const loadGrowthData = async (babyId: string, birthWeight?: number, birthLength?: number) => {
    try {
      console.log("Loading growth data for baby:", babyId);
      console.log("Birth weight:", birthWeight, "Birth length:", birthLength);
      
      const records = await getGrowthRecords(babyId);
      console.log("Growth records loaded:", records.length, "records");
      setGrowthRecords(records);
      
      // Get latest measurement for display
      const latest = await getLatestGrowthRecord(babyId);
      console.log("Latest growth record:", latest);
      
      if (latest) {
        setCurrentWeight(latest.weight.toString());
        setCurrentLength(latest.length.toString());
      } else if (birthWeight && birthLength) {
        // If no records yet, show birth measurements
        console.log("No growth records, using birth measurements");
        setCurrentWeight(birthWeight.toString());
        setCurrentLength(birthLength.toString());
      }
    } catch (error) {
      console.error("Error loading growth data:", error);
    }
  };

  const handleSelectSound = (sound: Sound) => {
    setSelectedSound(sound);
  };
  
  const handleSaveGrowth = async (weight: string, length: string) => {
    if (!babyId) return;
    
    try {
      await addGrowthRecord(babyId, weight, length);
      setCurrentWeight(weight);
      setCurrentLength(length);
      // Reload growth data
      await loadGrowthData(babyId, birthWeight || undefined, birthLength || undefined);
      setGrowthTrackingOpen(false);
    } catch (error) {
      console.error("Error saving growth record:", error);
      alert("Failed to save growth record");
    }
  };

  const handleGenerateSchedules = async () => {
    if (!babyId) return;
    
    Alert.alert(
      'Generate Schedules',
      'Generate vaccination and milestone schedules for your baby?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Generate',
          onPress: async () => {
            try {
              await generateVaccinationSchedule(babyId);
              await generateMilestoneSchedule(babyId);
              Alert.alert('Success', 'Schedules generated successfully!');
              loadUpcomingEvents(babyId);
            } catch (error) {
              Alert.alert('Error', 'Failed to generate schedules');
            }
          },
        },
      ]
    );
  };

  return (
    <View style={styles.container}>
      <Header
        childInitial={childInitial}
        babyName={babyName}
        avatarColor={avatarColor}
        avatarImage={avatarImage}
        onEditProfile={() => router.push("/babiesList")}
        onMessages={() => {}}
        onSettings={() => {}}
        unreadMessages={3}
      />
      
      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        <BabyMonitorStream babyName={babyName} />
        
        {/* Baby Sleep Activity */}
        <TouchableOpacity
          style={[styles.activityCard, styles.firstCard]}
          activeOpacity={0.7}
          onPress={() => setSleepHistoryOpen(true)}
        >
          <View style={styles.activityHeader}>
            <View style={styles.titleRow}>
              <Ionicons name="moon" size={18} color="#A2E884" />
              <Text style={styles.headerTitle}>Sleep Activity</Text>
            </View>
            <Ionicons name="chevron-forward" size={20} color="#999" />
          </View>
          
          <View style={styles.activityContent}>
            <View style={styles.activityRow}>
              <View style={styles.activityItem}>
                <View style={styles.timelineDot}>
                  <Ionicons name="bed-outline" size={16} color="white" />
                </View>
                <View style={styles.timelineContent}>
                  <Text style={styles.timelineLabel}>Fell Asleep</Text>
                  <Text style={styles.timelineTime}>14:30 PM</Text>
                </View>
              </View>
              <View style={styles.activityDivider} />
              <View style={styles.activityItem}>
                <View style={styles.timelineDot}>
                  <Ionicons name="sunny-outline" size={16} color="white" />
                </View>
                <View style={styles.timelineContent}>
                  <Text style={styles.timelineLabel}>Woke Up</Text>
                  <Text style={styles.timelineTime}>16:15 PM</Text>
                </View>
              </View>
            </View>
            
            <View style={styles.activitySummary}>
              <View style={styles.summaryItem}>
                <Text style={styles.activityLabel}>Last Sleep</Text>
                <Text style={styles.activityValue}>2h ago</Text>
              </View>
              <View style={styles.activityDivider} />
              <View style={styles.summaryItem}>
                <Text style={styles.activityLabel}>Duration</Text>
                <Text style={styles.activityValue}>1h 45m</Text>
              </View>
            </View>
          </View>
        </TouchableOpacity>
        
        <SoundPlayer
          onOpenLibrary={() => setIsLibraryOpen(true)}
          selectedSound={selectedSound}
        />

        {/* Growth Tracking */}
        <TouchableOpacity
          style={[styles.activityCard, { marginTop: 20 }]}
          activeOpacity={0.7}
          onPress={() => setGrowthTrackingOpen(true)}
        >
          <View style={styles.activityHeader}>
            <View style={styles.titleRow}>
              <Ionicons name="fitness" size={18} color="#A2E884" />
              <Text style={styles.headerTitle}>Growth Tracking</Text>
            </View>
            <Ionicons name="chevron-forward" size={20} color="#999" />
          </View>

          <View style={styles.activityContent}>
            <View style={styles.activityRow}>
              <View style={styles.activityItem}>
                <View style={styles.measurementIcon}>
                  <Ionicons name="scale-outline" size={20} color="white" />
                </View>
                <View style={styles.timelineContent}>
                  <Text style={styles.timelineLabel}>Weight</Text>
                  <Text style={styles.timelineTime}>{currentWeight} kg</Text>
                </View>
              </View>
              <View style={styles.activityDivider} />
              <View style={styles.activityItem}>
                <View style={styles.measurementIcon}>
                  <Ionicons name="resize-outline" size={20} color="white" />
                </View>
                <View style={styles.timelineContent}>
                  <Text style={styles.timelineLabel}>Length</Text>
                  <Text style={styles.timelineTime}>{currentLength} cm</Text>
                </View>
              </View>
            </View>

            <View style={styles.lastUpdated}>
              <Ionicons name="time-outline" size={14} color="#999" />
              <Text style={styles.lastUpdatedText}>Last updated: Today</Text>
            </View>
          </View>
        </TouchableOpacity>

        {/* Calendar */}
        <TouchableOpacity
          style={[styles.activityCard, { marginTop: 20 }]}
          activeOpacity={0.7}
          onPress={() => setCalendarOpen(true)}
        >
          <View style={styles.activityHeader}>
            <View style={styles.titleRow}>
              <Ionicons name="calendar" size={18} color="#A2E884" />
              <Text style={styles.headerTitle}>Upcoming Events</Text>
            </View>
            <Ionicons name="chevron-forward" size={20} color="#999" />
          </View>

          <View style={styles.activityContent}>
            {upcomingEvents.length > 0 ? (
              upcomingEvents.map((event, index) => {
                const eventDate = new Date(event.date);
                const now = new Date();
                const isPast = eventDate < now && !event.completed;
                const isToday = eventDate.toDateString() === now.toDateString();
                
                const eventTypeColors: Record<string, string> = {
                  vaccination: '#FF6B6B',
                  checkup: '#4ECDC4',
                  milestone: '#FFD93D',
                  medication: '#A2E884',
                  appointment: '#6B4FA0',
                  other: '#95A5A6',
                };

                return (
                  <View key={event._id}>
                    {index > 0 && <View style={styles.eventDivider} />}
                    <TouchableOpacity 
                      style={[styles.eventRow, isPast && styles.pastEventRow]}
                      onPress={() => setCalendarOpen(true)}
                      activeOpacity={0.7}
                    >
                      <View style={[styles.eventTypeBadge, { backgroundColor: eventTypeColors[event.type], opacity: isPast ? 0.5 : 1 }]}>
                        <Ionicons 
                          name={event.type === 'vaccination' ? 'medical' : event.type === 'milestone' ? 'star' : 'calendar'} 
                          size={14} 
                          color="white" 
                        />
                      </View>
                      <View style={styles.eventDetails}>
                        <View style={styles.eventTitleRow}>
                          <Text style={[styles.eventTitle, isPast && styles.pastEventText]}>
                            {event.title}
                          </Text>
                          {event.completed && (
                            <View style={styles.completedBadge}>
                              <Ionicons name="checkmark-circle" size={16} color="#A2E884" />
                            </View>
                          )}
                          {isPast && !event.completed && (
                            <View style={styles.overdueBadge}>
                              <Text style={styles.overdueText}>Overdue</Text>
                            </View>
                          )}
                          {isToday && !event.completed && (
                            <View style={styles.todayBadge}>
                              <Text style={styles.todayBadgeText}>Today</Text>
                            </View>
                          )}
                        </View>
                        <Text style={[styles.eventDateText, isPast && styles.pastEventText]}>
                          {eventDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                          {event.time && ` at ${event.time}`}
                        </Text>
                      </View>
                    </TouchableOpacity>
                  </View>
                );
              })
            ) : (
              <View style={styles.noEventsContainer}>
                <Ionicons name="calendar-outline" size={32} color="#CCC" />
                <Text style={styles.noEventsText}>No upcoming events</Text>
                <Text style={styles.noEventsSubtext}>Tap to add or generate schedules</Text>
              </View>
            )}
            
            {!hasAutoGeneratedEvents && (
              <TouchableOpacity 
                style={styles.generateSchedulesButton}
                onPress={handleGenerateSchedules}
                activeOpacity={0.7}
              >
                <Ionicons name="medical" size={18} color="#A2E884" />
                <Text style={styles.generateSchedulesText}>Generate Schedules</Text>
              </TouchableOpacity>
            )}
          </View>
        </TouchableOpacity>

        {/* Recent Memories */}
        <TouchableOpacity
          style={[styles.activityCard, { marginTop: 20 }]}
          activeOpacity={0.7}
          onPress={() => router.push("/jurnal")}
        >
          <View style={styles.activityHeader}>
            <View style={styles.titleRow}>
              <Ionicons name="book" size={18} color="#A2E884" />
              <Text style={styles.headerTitle}>Recent Memories</Text>
            </View>
            <Ionicons name="chevron-forward" size={20} color="#999" />
          </View>

          <View style={styles.activityContent}>
            {recentMemories.length > 0 ? (
              recentMemories.map((memory, index) => {
                const memoryDate = new Date(memory.date);
                const MOOD_ICONS: Record<string, string> = {
                  happy: "😄",
                  okay: "🙂",
                  neutral: "😐",
                  crying: "😢",
                  sick: "🤒",
                };

                return (
                  <View key={memory._id}>
                    {index > 0 && <View style={styles.eventDivider} />}
                    <View style={styles.memoryRow}>
                      <View style={styles.memoryIcon}>
                        <Text style={styles.memoryMood}>{MOOD_ICONS[memory.mood]}</Text>
                      </View>
                      <View style={styles.memoryDetails}>
                        {memory.title && (
                          <Text style={styles.memoryTitle} numberOfLines={1}>
                            {memory.title}
                          </Text>
                        )}
                        <Text style={styles.memoryDescription} numberOfLines={2}>
                          {memory.description}
                        </Text>
                        <Text style={styles.memoryDate}>
                          {memoryDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                        </Text>
                      </View>
                      {memory.photos.length > 0 && (
                        <Image
                          source={{ uri: `http://192.168.1.10:5000${memory.photos[0]}` }}
                          style={styles.memoryThumbnail}
                        />
                      )}
                    </View>
                  </View>
                );
              })
            ) : (
              <View style={styles.noEventsContainer}>
                <Ionicons name="book-outline" size={32} color="#CCC" />
                <Text style={styles.noEventsText}>No memories yet</Text>
                <Text style={styles.noEventsSubtext}>Tap to start capturing moments</Text>
              </View>
            )}
          </View>
        </TouchableOpacity>
      </ScrollView>
      
      <SoundLibraryModal
        visible={isLibraryOpen}
        onClose={() => setIsLibraryOpen(false)}
        onSelectSound={handleSelectSound}
      />

      <SleepHistoryModal
        visible={sleepHistoryOpen}
        onClose={() => setSleepHistoryOpen(false)}
      />

      <GrowthTrackingModal
        visible={growthTrackingOpen}
        onClose={() => setGrowthTrackingOpen(false)}
        onSave={handleSaveGrowth}
        growthRecords={growthRecords}
        birthWeight={birthWeight}
        birthLength={birthLength}
        birthDate={birthDate}
      />

      <CalendarModal
        visible={calendarOpen}
        onClose={() => setCalendarOpen(false)}
        babyId={babyId || ''}
        onEventsUpdate={() => babyId && loadUpcomingEvents(babyId)}
      />
      
      {/* Floating Chat Button */}
      <TouchableOpacity
        style={styles.chatButton}
        activeOpacity={0.85}
        onPress={() => setChatOpen(true)}
      >
        <Ionicons name="chatbubbles" size={32} color="white" />
      </TouchableOpacity>

      <ChatbotModal visible={chatOpen} onClose={() => setChatOpen(false)} />

      <Footer 
        active="Home" 
        onNavigate={(screen) => {
          if (screen === 'Calendar') {
            setCalendarOpen(true);
          } else if (screen === 'Home') {
            router.push('/dashboard');
          } else if (screen === 'Raports') {
            router.push('/raports');
          } else if (screen === 'Tips') {
            router.push('/tips');
          } else if (screen === 'Jurnal') {
            router.push('/jurnal');
          }
        }} 
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF8F0",
  },
  content: {
    flex: 1,
  },
  chatButton: {
    position: 'absolute',
    bottom: 90,
    right: 24,
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: '#A2E884',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  activityCard: {
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  firstCard: {
    marginTop: 8,
  },
  activityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#A2E884',
  },
  activityContent: {
    gap: 16,
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  activityItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  activityLabel: {
    fontSize: 14,
    color: '#999',
    marginBottom: 4,
    fontWeight: '500',
  },
  activityValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#333',
  },
  activityDivider: {
    width: 1,
    height: 50,
    backgroundColor: '#E0E0E0',
    marginHorizontal: 16,
  },
  activitySummary: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  summaryItem: {
    flex: 1,
    alignItems: 'center',
  },
  timelineDot: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#A2E884',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#A2E884',
    shadowOpacity: 0.3,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  timelineContent: {
    alignItems: 'center',
  },
  timelineLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#999',
    marginBottom: 4,
  },
  timelineTime: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
  },
  measurementIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#A2E884',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#A2E884',
    shadowOpacity: 0.3,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  lastUpdated: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  lastUpdatedText: {
    fontSize: 12,
    color: '#999',
    fontWeight: '500',
  },
  eventDivider: {
    height: 1,
    backgroundColor: '#F0F0F0',
    marginVertical: 12,
  },
  eventRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  pastEventRow: {
    opacity: 0.6,
  },
  eventTypeBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  eventDetails: {
    flex: 1,
  },
  eventTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  eventTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  pastEventText: {
    color: '#999',
  },
  completedBadge: {
    marginLeft: 4,
  },
  overdueBadge: {
    backgroundColor: '#FFE5E5',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  overdueText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#FF6B6B',
  },
  todayBadge: {
    backgroundColor: '#E5F7E5',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  todayBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#4CAF50',
  },
  eventDateText: {
    fontSize: 12,
    color: '#666',
  },
  noEventsContainer: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  noEventsText: {
    fontSize: 14,
    color: '#999',
    fontWeight: '500',
    marginTop: 8,
  },
  noEventsSubtext: {
    fontSize: 12,
    color: '#BBB',
    marginTop: 4,
  },
  generateSchedulesButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#F0F9F0',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#A2E884',
  },
  generateSchedulesText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#A2E884',
  },
  memoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  memoryIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F0F9F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  memoryMood: {
    fontSize: 20,
  },
  memoryDetails: {
    flex: 1,
  },
  memoryTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  memoryDescription: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
    marginBottom: 4,
  },
  memoryDate: {
    fontSize: 11,
    color: '#999',
    fontWeight: '500',
  },
  memoryThumbnail: {
    width: 60,
    height: 60,
    borderRadius: 8,
  },
});

export default DashboardPage;
