import mongoose from "mongoose";

const calendarEventSchema = new mongoose.Schema({
   babyId: {
       type: mongoose.Schema.Types.ObjectId,
       ref: "Baby",
       required: true,
       index: true
   },
   title: {
       type: String,
       required: true,
       trim: true
   },
   description: {
       type: String,
       trim: true
   },
   date: {
       type: Date,
       required: true,
       index: true
   },
   time: {
       type: String, // e.g., "14:30" or null for all-day events
       default: null
   },
   type: {
       type: String,
       required: true,
       enum: ['vaccination', 'checkup', 'milestone', 'medication', 'appointment', 'other'],
       default: 'other'
   },
   completed: {
       type: Boolean,
       default: false
   },
   reminder: {
       type: Boolean,
       default: false
   },
   reminderDays: {
       type: Number, // Days before event to remind
       default: 1
   },
   autoGenerated: {
       type: Boolean,
       default: false // True for vaccination schedule items
   },
   notes: {
       type: String,
       trim: true
   }
}, {timestamps: true});

// Compound indexes for efficient queries
calendarEventSchema.index({ babyId: 1, date: 1 });
calendarEventSchema.index({ babyId: 1, type: 1 });

const CalendarEvent = mongoose.model("CalendarEvent", calendarEventSchema);
export default CalendarEvent;



